### PR TITLE
chore: update build trigger for 8.3.0

### PR DESCRIPTION
**Pull request by Xerkus**
PHP 8.3.0 just released

I believe this is blocked by https://github.com/php-build/php-build/pull/759

### CODE REVIEW

**Review by rarkins — APPROVED** [review]

**Comment by rarkins** [comment]
@viceice any ideas?

image

**Comment by viceice** [comment]
> @viceice any ideas?
> 
> image

merge group was missing on workflow trigger

**Comment by Xerkus** [comment]
How did this get built considering that php-build does not have 8.3.0 yet? Is it no longer a dependency?

**Comment by viceice** [comment]
it's not build until that definition updated is merged.

currently PHP 8.3 isn't on docker hub, so it's not tried to build.

**Comment by viceice** [comment]
this trigger file is just to get commits to main to trigger GitHub actions. the action is then trying to build all missing PHP versions (besides explicit excluded via config)

**Pull request merged**
